// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package protoClasses;

public final class StudentOuterClass {
  private StudentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoClasses_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoClasses_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\022\014protoClasses\"\360\001\n\007Studen" +
      "t\022\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\0222\n\tphonetype" +
      "\030\003 \001(\0162\037.protoClasses.Student.PhoneType\022" +
      "2\n\tclassyear\030\005 \001(\0162\037.protoClasses.Studen" +
      "t.ClassYear\"!\n\tPhoneType\022\n\n\006MOBILE\020\001\022\010\n\004" +
      "HOME\020\002\"@\n\tClassYear\022\014\n\010FRESHMAN\020\001\022\r\n\tSOP" +
      "HOMORE\020\002\022\n\n\006JUNIOR\020\003\022\n\n\006SENIOR\020\004B\002P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protoClasses_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protoClasses_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoClasses_Student_descriptor,
        new java.lang.String[] { "Name", "Id", "Phonetype", "Classyear", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
