// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package protoClasses;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protoClasses.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required int32 id = 2;</code>
   */
  boolean hasId();
  /**
   * <code>required int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>optional .protoClasses.Student.PhoneType phonetype = 3;</code>
   */
  boolean hasPhonetype();
  /**
   * <code>optional .protoClasses.Student.PhoneType phonetype = 3;</code>
   */
  protoClasses.Student.PhoneType getPhonetype();

  /**
   * <code>optional .protoClasses.Student.ClassYear classyear = 5;</code>
   */
  boolean hasClassyear();
  /**
   * <code>optional .protoClasses.Student.ClassYear classyear = 5;</code>
   */
  protoClasses.Student.ClassYear getClassyear();
}
